version: '3.8'

services:
  openresty:
    image: openresty
    container_name: openresty_reverse_proxy
    extra_hosts:
      - "virtual.example.com:127.0.0.1"
      - "target.example.com:172.17.0.1"
      - "proxy.example.com:172.17.0.1"
      - "tundra.volutega.com:127.0.0.1"
    ports:
      - "8001:80"
    environment:
      SQUID_PROXY_HOST: "http://tundra.volutega.com:3128"  # Замените на ваш http-прокси
      TARGET_HOST: "http://target.example.com:5000"          # Замените на целевой сайт
      VIRTUAL_HOST: "tundra.volutega.com"               # Замените на имя виртуального хоста
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      #- ./lua:/usr/local/openresty/lua:ro
    restart: unless-stopped

  squid:
    image: sameersbn/squid:latest
    container_name: squid_proxy
    extra_hosts:
      - "virtual.example.com:172.17.0.1"
      - "target.example.com:172.17.0.1"
      - "proxy.example.com:172.17.0.1"
    ports:
      - "3128:3128"
    environment:
      TZ: "UTC"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
    restart: unless-stopped

  http_logger_app:
    build:
      context: ./http_logger_app
    container_name: http_logger_app
    extra_hosts:
      - "virtual.example.com:172.17.0.1"
      - "target.example.com:172.17.0.1"
      - "proxy.example.com:172.17.0.1"
    ports:
      - "5000:5000"
    environment:
      LOG_HEADERS: "true"
      LOG_CONTENT: "true"
      LOG_SIZE: "true"
    volumes:
      - ./http_logger_app:/app
    working_dir: /app
    command: python3 app.py
    restart: unless-stopped    