version: '3.8'

services:
  http_logger_app:
    build:
      context: ./http_logger_app
    container_name: http_logger_app
    extra_hosts:
      - "virtual.example.com:172.17.0.1"
      - "target.example.com:172.17.0.1"
      - "proxy.example.com:172.17.0.1"
    ports:
      - "5000:5000"
    environment:
      LOG_HEADERS: "true"
      LOG_CONTENT: "true"
      LOG_SIZE: "true"
    volumes:
      - ./http_logger_app:/app
    working_dir: /app
    command: python3 app.py
    restart: unless-stopped    
